[package]
name = "cmt"
version = "0.1.0"
edition = "2021"
description = "A CLI tool that generates commit messages using OpenAI"
authors = ["Clifton King <cliftonk@gmail.com>"]

[dependencies]
git2 = "0.20.0"
colored = "3.0.0"
reqwest = { version = "0.12.0", features = ["json", "blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.105"
dotenv = "0.15.0"
clap = { version = "4.5", features = ["derive"] }
