[package]
name = "cmt"
version = "0.3.3"
edition = "2021"
description = "A CLI tool that generates commit messages using OpenAI or Anthropic Claude"
authors = ["Clifton King <cliftonk@gmail.com>"]
license = "MIT"
repository = "https://github.com/cliftonk/cmt"
homepage = "https://github.com/cliftonk/cmt"
documentation = "https://github.com/cliftonk/cmt#readme"
readme = "README.md"
keywords = ["git", "commit", "openai", "claude", "gpt"]
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::build-utils",
]

[dependencies]
git2 = { version = "0.20.0", default-features = false }
colored = "3.0.0"
reqwest = { version = "0.12.0", features = [
  "json",
  "blocking",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.105"
dotenv = "0.15.0"
clap = { version = "4.5", features = ["derive", "std"] }

[profile.release]
opt-level = "z"   # Optimize for size
lto = true
codegen-units = 1
strip = true
panic = "abort"   # Remove panic unwinding code
