[package]
name = "cmt"
version = "0.3.1"
edition = "2021"
description = "A CLI tool that generates commit messages using OpenAI or Anthropic Claude"
authors = ["Clifton King <cliftonk@gmail.com>"]
license = "MIT"
repository = "https://github.com/cliftonk/cmt"
homepage = "https://github.com/cliftonk/cmt"
documentation = "https://github.com/cliftonk/cmt#readme"
readme = "README.md"
keywords = ["git", "commit", "openai", "claude", "gpt"]
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::build-utils",
]

[dependencies]
git2 = "0.20.0"
colored = "3.0.0"
reqwest = { version = "0.12.0", features = ["json", "blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.105"
dotenv = "0.15.0"
clap = { version = "4.5", features = ["derive"] }
anthropic = { version = "0.0.8" }
tokio = { version = "1.36", features = ["rt", "rt-multi-thread"] }
